#!/bin/sh
uci set mosdns.config.enabled='1'
uci set mosdns.config.redirect='0'
uci set mosdns.config.custom_local_dns='1'
uci set mosdns.config.dns_leak='1'
uci add_list mosdns.config.local_dns='https://dns.alidns.com/dns-query'
uci add_list mosdns.config.local_dns='https://doh.pub/dns-query'
uci add_list mosdns.config.local_dns='https://doh.360.cn/dns-query'
uci add_list mosdns.config.remote_dns='tls://1.1.1.1'
uci add_list mosdns.config.remote_dns='tls://8.8.8.8'
uci add_list mosdns.config.remote_dns='tls://9.9.9.9'
uci add_list mosdns.config.remote_dns='tls://208.67.222.222'
uci commit mosdns
uci set luci.main.mediaurlbase='/luci-static/bootstrap'
uci commit luci
uci set fancontrol.settings.fan_file='/sys/devices/virtual/thermal/cooling_device1/cur_state'
uci commit fancontrol
sed -i "s/option rollback '60'/option rollback '30'/" /etc/config/luci
sed -i "s/option holdoff '4'/option holdoff '2'/" /etc/config/luci
sed -i "s/option timeout '5'/option timeout '3'/" /etc/config/luci
sed -i "s/option display '1.5'/option display '1'/" /etc/config/luci
uci del firewall.cfg01e63d.flow_offloading
uci del firewall.cfg01e63d.flow_offloading_hw
uci commit firewall
uci commit
until [ "$( opkg list-installed 2>/dev/null| grep -c "^kernel")" -ne '0' ]; do
  sleep 1
done
if [ "$(grep -c "/proc/sys/vm/drop_caches" /etc/crontabs/root)" -eq '0' ];then
  echo "0 */1 * * * sync && echo 3 > /proc/sys/vm/drop_caches" >>/etc/crontabs/root
fi
if [-e /sys/class/leds/white:system/brightness ] && [ "$(grep -c "30 23 * * * echo "0" > /sys/class/leds/white:system/brightness" /etc/crontabs/root)" -eq '0' ];then
  echo "30 23 * * * echo "0" > /sys/class/leds/white:system/brightness" >>/etc/crontabs/root
fi
if [-e /sys/class/leds/white:system/brightness ] && [ "$(grep -c "00 05 * * * echo "1" > /sys/class/leds/white:system/brightness" /etc/crontabs/root)" -eq '0' ];then
  echo "00 05 * * * echo "1" > /sys/class/leds/white:system/brightness" >>/etc/crontabs/root
fi
if [ "$(opkg list-installed 2>/dev/null | grep -c "^luci-app-tailscale")" -ne '0' ] && [ "$(cat /usr/share/luci/menu.d/luci-app-tailscale.json | grep -c "services")" -ne '0' ]; then
  sed -i 's/services/vpn/g' /usr/share/luci/menu.d/luci-app-tailscale.json && rm -rf luci-indexcache.*.json
  need_restart=1
fi
if [ "$(opkg list-installed 2>/dev/null | grep -c "^luci-app-ttyd")" -ne '0' ] && [ "$(cat /usr/share/luci/menu.d/luci-app-ttyd.json | grep -c "services")" -ne '0' ]; then
  sed -i 's/services/system/g' /usr/share/luci/menu.d/luci-app-ttyd.json && rm -rf luci-indexcache.*.json
  need_restart=1
fi
if [ "$need_restart" -eq '1' ]; then
  /etc/init.d/rpcd restart

fi
exit 0
