#!/bin/sh
uci set turboacc.config.sw_flow='0'
uci commit turboacc
uci set mosdns.config.enabled='1'
uci set mosdns.config.redirect='0'
uci set mosdns.config.custom_local_dns='1'
uci set mosdns.config.enable_http3_local='0'
uci add_list mosdns.config.local_dns='https://dns.alidns.com/dns-query'
uci add_list mosdns.config.local_dns='https://doh.pub/dns-query'
uci add_list mosdns.config.local_dns='https://doh.360.cn/dns-query'
uci add_list mosdns.config.remote_dns='tls://1.1.1.1'
uci add_list mosdns.config.remote_dns='tls://8.8.8.8'
uci add_list mosdns.config.remote_dns='tls://9.9.9.9'
uci add_list mosdns.config.remote_dns='tls://208.67.222.222'
uci commit mosdns
uci del system.ntp.enabled
uci del system.ntp.enable_server
uci set system.cfg01e48a.zonename='Asia/Shanghai'
uci set system.cfg01e48a.timezone='CST-8'
uci set system.cfg01e48a.log_proto='udp'
uci set system.cfg01e48a.conloglevel='8'
uci set system.cfg01e48a.cronloglevel='5'
uci commit system
echo "0 */1 * * * sync && echo 3 > /proc/sys/vm/drop_caches" >>/etc/crontabs/root
opkg install /usr/share/fan-control_2-26_all.ipk
cp /usr/share/fan_monitor /usr/sbin/fan_monitor
chmod +x /usr/sbin/fan_monitor
/etc/init.d/fan_control restart
sed -i "s/option rollback '60'/option rollback '30'/" /etc/config/luci
sed -i "s/option holdoff '4'/option holdoff '1'/" /etc/config/luci
sed -i "s/option timeout '5'/option timeout '3'/" /etc/config/luci
sed -i "s/option display '1.5'/option display '1'/" /etc/config/luci
config_content="
config dns_servers
	option enabled '1'
	option group 'nameserver'
	option type 'tcp'
	option interface 'Disable'
	option node_resolve '0'
	option specific_group 'Disable'
	option ip '127.0.0.1'
	option port '5335'

config dns_servers
	option enabled '1'
	option group 'nameserver'
	option type 'udp'
	option interface 'Disable'
	option node_resolve '0'
	option specific_group 'Disable'
	option ip '127.0.0.1'
	option port '5335'

config dns_servers
	option enabled '1'
	option group 'nameserver'
	option type 'tls'
	option interface 'Disable'
	option node_resolve '0'
	option specific_group 'Disable'
	option ip '127.0.0.1'
	option port '5335'

config dns_servers
	option enabled '1'
	option group 'nameserver'
	option type 'https'
	option interface 'Disable'
	option node_resolve '0'
	option specific_group 'Disable'
	option ip '127.0.0.1'
	option port '5335'

config dns_servers
	option enabled '1'
	option group 'fallback'
	option type 'tcp'
	option interface 'Disable'
	option node_resolve '0'
	option specific_group 'Disable'
	option ip '127.0.0.1'
	option port '5335'

config dns_servers
	option enabled '1'
	option group 'fallback'
	option type 'udp'
	option interface 'Disable'
	option node_resolve '0'
	option specific_group 'Disable'
	option ip '127.0.0.1'
	option port '5335'

config dns_servers
	option enabled '1'
	option group 'fallback'
	option type 'tls'
	option interface 'Disable'
	option node_resolve '0'
	option specific_group 'Disable'
	option ip '127.0.0.1'
	option port '5335'

config dns_servers
	option enabled '1'
	option group 'fallback'
	option type 'https'
	option interface 'Disable'
	option node_resolve '0'
	option specific_group 'Disable'
	option ip '127.0.0.1'
	option port '5335'
"
echo "$config_content" >> /etc/config/openclash
exit 0
