#!/bin/sh
uci set turboacc.config.sw_flow='0'
uci commit turboacc
echo "0 */1 * * * sync && echo 3 > /proc/sys/vm/drop_caches" >>/etc/crontabs/root
opkg install /usr/share/fan-control_2-26_all.ipk
cp /usr/share/fan_monitor /usr/sbin/fan_monitor
chmod +x /usr/sbin/fan_monitor
/etc/init.d/fan_control restart
sed -i "s/option rollback '60'/option rollback '30'/" /etc/config/luci
sed -i "s/option holdoff '4'/option holdoff '1'/" /etc/config/luci
sed -i "s/option timeout '5'/option timeout '3'/" /etc/config/luci
sed -i "s/option display '1.5'/option display '1'/" /etc/config/luci
exit 0
