#!/bin/sh
uci set mosdns.config.enabled='1'
uci set mosdns.config.redirect='1'
uci set mosdns.config.custom_local_dns='1'
uci set mosdns.config.enable_http3_local='0'
uci set mosdns.config.dns_leak='1'
uci add_list mosdns.config.local_dns='https://dns.alidns.com/dns-query'
uci add_list mosdns.config.local_dns='https://doh.pub/dns-query'
uci add_list mosdns.config.local_dns='https://doh.360.cn/dns-query'
uci add_list mosdns.config.remote_dns='https://doh.opendns.com/dns-query'
uci add_list mosdns.config.remote_dns='https://dns.google/dns-query'
uci add_list mosdns.config.remote_dns='https://dns.cloudflare.com/dns-query'
uci add_list mosdns.config.remote_dns='https://dns.quad9.net/dns-query'
uci commit mosdns
uci set luci.main.mediaurlbase='/luci-static/bootstrap'
uci commit luci
uci set turboacc.config.bbr_cca='1'
uci commit turbooacc
#echo "0 */1 * * * sync && echo 3 > /proc/sys/vm/drop_caches" >>/etc/crontabs/root
sed -i "s/option rollback '90'/option rollback '30'/" /etc/config/luci
sed -i "s/option holdoff '4'/option holdoff '2'/" /etc/config/luci
sed -i "s/option timeout '5'/option timeout '3'/" /etc/config/luci
sed -i "s/option display '1.5'/option display '1'/" /etc/config/luci
exit 0
