name: Build filogic

on:
  schedule:
    - cron: '0 2 */4 * *'
  workflow_dispatch:
    inputs:
      docker:
        description: '是否编译 docker'
        required: false
        default: 'false'

jobs:
  build:
    name: 编译 ${{ matrix.device }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - device: GL-MT5000
            repo_url: https://github.com/m0eak/fanchmwrt.git
            repo_branch: mt5000
            config_file: ./config/mt5000.config
            workflow_name: GL-MT5000
            sonic_fullcone: "true"
          - device: Tenda-BE12PRO
            repo_url: https://github.com/sukerxi/m798x-tdbe.git
            repo_branch: tenda-be12-pro
            config_file: ./config/be12pro.config
            workflow_name: Tenda-BE12PRO
            sonic_fullcone: "false"
    uses: ./.github/workflows/_openwrt-build-device.yml
    with:
      device: ${{ matrix.device }}
      config_file: ${{ matrix.config_file }}
      workflow_name: ${{ matrix.workflow_name }}
      repo_url: ${{ matrix.repo_url }}
      repo_branch: ${{ matrix.repo_branch }}
      install_automake_117: "true"
      sonic_fullcone: ${{ matrix.sonic_fullcone }}
      extra_config_file: ${{ github.event.inputs.docker == 'true' && './config/docker.config' || '' }}

  publish_release:
    name: 合并并发布固件
    needs: build
    runs-on: ubuntu-22.04
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Publish release
        uses: ./.github/actions/openwrt-publish-release
        with:
          release-tag-prefix: filogic
          release-files: |
            all-artifacts/firmware-*/*.manifest
            all-artifacts/firmware-*/*sysupgrade.bin
            all-artifacts/firmware-*/*factory.bin
            all-artifacts/firmware-*/*initramfs-kernel.bin
            all-artifacts/firmware-*/*-version.buildinfo
            all-artifacts/firmware-*/*-sha256sums
            all-artifacts/firmware-*/*-profiles.json
            all-artifacts/firmware-*/*-config.buildinfo
            all-artifacts/firmware-*/*-feeds.buildinfo
